config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  get '/about' => 'static#about'
  get '/cat-pictures' => 'static#cats', as: :cats

  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks

  get '/sign-in' => 'sessions#new'
  delete '/sign-out' => 'sessions#destroy'

end

app/models/task.rb
class Task < ActiveRecord::Base
	validates_presence_of :name, message: "Name is required"
	validate :not_past_date

	def not_past_date
	  if self.days.past?
	    errors.add(:days, 'Date cannot be in the past')
	  end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def user_signed_in?
    !!current_user
  end
  helper_method :user_signed_in?
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged In!'
    else
      flash.alert = 'Invalid username or password. Please try again!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'successfully signed out'
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def cats
    @cats = CatAPI.new.get_images(results_per_page: params[:number_of_cats] || 9)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :time_update, only: [:update, :create]
  
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :time, :duration, :category, :subtasks, :notes, :recurring, :days)
    end

    def time_update
      params[:task][:duration] = params[:hours].to_i * 60 + params[:minutes].to_i
    end

    def redirect_to_login
      if !user_signed_in?
        redirect_to sign_in_path
      end
    end

    helper_method :redirect_to_login
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builders/responsive_grid.rb
# Helper class for dynamically building responsive_grid elements on the page. Simplifies
# a lot of the ceremony in building up all the divs and classes.
class Builders::ResponsiveGrid

  DEFAULT_ITEMS_PER_ROW = 3
  MAX_GRID_COLUMNS = 12

  attr_reader :template
  delegate :capture, :content_tag, to: :template

  # @overload initialize( collection, options, &block )
  def initialize( collection, options={}, template, &block )
    options[:xs] ||= options[:sm] ||= options[:md] ||= options[:lg] ||= DEFAULT_ITEMS_PER_ROW

    @collection = collection
    @options    = options
    @block      = block
    @template   = template
  end

  def render
    options = @options.merge class: "responsive-grid #{@options[:class]}"

    content_tag :div, options.except(:lg, :md, :sm, :xs) do
      content_tag :div, rendered_grid_items, class: 'row'
    end
  end

private

  def rendered_grid_items
    @collection.map do |item|
      content_tag :div, capture( item, &@block ), class: "grid-item #{responsive_columns}"
    end.join.html_safe
  end

  def responsive_columns
    columns = ''

    %i{lg md sm xs}.each do |size|
      columns += case @options[size]
      when 1,2,3,4,6,12 then "col-#{size}-#{MAX_GRID_COLUMNS / @options[size]} "
      else                   "col-#{size}-#{@options[size]}ths "
      end
    end

    columns
  end

end

app/helpers/builders_helper.rb
module BuildersHelper
  def responsive_grid( collection, options={}, &block )
    Builders::ResponsiveGrid.new( collection, options, self, &block ).render
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
  def current_date_and_time
    Time.now.strftime('%B %-d, %Y at %-l:%M%P')
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
	def time_hours num
		(num.to_i / 60).to_i
	end

	def time_minutes num
		num.to_i % 60
	end
end

app/views/layouts/application.html.slim
doctype html
html

  head

    title Project8
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    - flash.each do |type, message|
      div class="flash #{type}"
        p = message

    header.container
      nav
        ul
          li
            = link_to root_path do
              h1 Tasks n Cats
          li= link_to 'About', about_path
          li= link_to 'Cats', cats_path
          li= link_to 'Schedule', tasks_path
          - if user_signed_in?
            li.pull-right= link_to "Sign Out", sign_out_path, method: :delete
            li.greeting.pull-right
              small
                = 'Hello, ' + current_user.email
          - else
            li.pull-right= link_to "Sign In", sign_in_path

    .container
      = yield

app/views/tasks/_form.html.slim
- redirect_to_login

= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      h3 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @task.errors.each do |attr, message|
          li = message

  .field.col-md-12.heading
    = f.label :name
    = f.text_field :name
  .field.col-md-4
    .input-group.clockpicker data-autoclose="true"
      = f.label :time
      .form-group
        = f.text_field :time, class: "form-control"
        span.input-group-addon
          span.glyphicon.glyphicon-time
    javascript:
      $('.clockpicker').clockpicker();
  .field.col-md-4.split-time
    = f.label :duration
    = number_field_tag :hours, value = (time_hours @task.duration), min: 0
    '  :
    = number_field_tag :minutes, value = (time_minutes @task.duration), min: 0, max: 59, step: 5
  .field.col-md-4
    = f.label :category
    = f.text_field :category
  .field.col-md-4
    = f.label :subtasks
    = f.text_area :subtasks
  .field.col-md-4
    = f.label :notes
    = f.text_area :notes
  .field.col-md-4
    = f.label :recurring
    = f.check_box :recurring
  .field.col-md-4
    = f.label :days, "Date"
    = f.date_field :days
  .actions.col-md-4 = f.submit
  .clearfix

app/views/tasks/edit.html.slim
h1 Editing task

== render 'form'

= link_to 'Show', @task
'|
= link_to 'Back', tasks_path

app/views/tasks/index.html.slim
h1 Listing tasks

table
  thead
    tr
      th Name
      th Time
      th Duration
      th Category
      th Subtasks
      th Notes
      th Recurring
      th Days
      th
      th
      th

  tbody
    - @tasks.each do |task|
      tr
        td = task.name
        td = task.time.try(:stamp, '9:20 am')
        td
          = time_hours task.duration
          | :
          = time_minutes task.duration
        td = task.category
        td = task.subtasks
        td = task.notes
        td = task.recurring
        td = task.days
        td = link_to 'Show', task
        - if user_signed_in?
          td = link_to 'Edit', edit_task_path(task)
          td = link_to 'Destroy', task, data: {:confirm => 'Are you sure?'}, :method => :delete

br

- if user_signed_in?
  =link_to '+ New Task', new_task_path

app/views/tasks/new.html.slim
h2 New task

== render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.slim
p#notice = notice

p
  strong Name:
  = @task.name
p
  strong Time:
  = @task.time.try(:stamp,'2:00 pm')
p
  strong Duration: 
  = time_hours @task.duration
  |:
  = time_minutes @task.duration
p
  strong Category:
  = @task.category
p
  strong Subtasks:
  = @task.subtasks
p
  strong Notes:
  = @task.notes
p
  strong Recurring:
  = @task.recurring
p
  strong Days:
  = @task.days
- if user_signed_in?
  = link_to 'Edit', edit_task_path(@task)
  '  |
= link_to 'Back', tasks_path